buildscript {
    repositories {
        maven {
            url = 'https://maven.minecraftforge.net/'
        }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:6.0.+'
    }
}

apply plugin: 'net.minecraftforge.gradle'

version = '1.0'
group = 'com.example.dontcuttripwire' // 确保与包名一致
archivesBaseName = 'dontcuttripwire'

minecraft {
    mappings channel: 'official', version: '1.20.1'
    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                dontcuttripwire {
                    source sourceSets.main
                }
            }
        }
        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                dontcuttripwire {
                    source sourceSets.main
                }
            }
        }
    }
}

repositories {
    maven {
        url = 'https://maven.minecraftforge.net/'
    }
    mavenCentral()
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.2.32'
}

jar {
    manifest {
        attributes([
                'Specification-Title'   : 'dontcuttripwire',
                'Specification-Vendor'  : 'example',
                'Specification-Version' : '1', // We are version 1 of ourselves
                'Implementation-Title'  : project.name,
                'Implementation-Version': version,
                'Implementation-Vendor' : 'example',
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}